[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/sclevine/spec"
  branch = "master"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.1.1"

[[constraint]]
  branch = "master"
  name = "github.com/buildpack/packs"
